# Generated by Django 4.2.16 on 2024-11-08 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ordered_model.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submission", "0075_increase_resource_link_length"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="SubmissionSpeakerThroughModel",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True, primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "submission",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="submission.submission",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "submission_submission_speakers",
                        "ordering": ("submission", "order"),
                    },
                ),
                migrations.AlterField(
                    model_name="submission",
                    name="speakers",
                    field=ordered_model.fields.OrderedManyToManyField(
                        related_name="submissions",
                        through="submission.SubmissionSpeakerThroughModel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ]
        ),
        migrations.AddField(
            model_name="SubmissionSpeakerThroughModel",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False
        ),
    ]
